backend:
  name: git
  repo: ahmed-farag36/test-decap-cms # Replace with your GitHub repository
  branch: main # Or the branch you use

media_folder: "public/uploads" # Where uploaded media files are stored
public_folder: "/uploads"     # URL path to access media files

collections:
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: body, label: Body, widget: markdown }
